"""empty message

Revision ID: 4ffc6cb2e823
Revises: 
Create Date: 2023-06-15 00:22:44.743486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffc6cb2e823'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('worker_id', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('disciples', sa.String(length=1000), nullable=True),
    sa.Column('reports', sa.String(length=50), nullable=False),
    sa.Column('pastor', sa.String(length=50), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('worker_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_table('followup_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('comment_followup', sa.Text(), nullable=True),
    sa.Column('person', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_table('outreach_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('total_reached', sa.Integer(), nullable=False),
    sa.Column('saved', sa.Integer(), nullable=False),
    sa.Column('already_saved', sa.Integer(), nullable=False),
    sa.Column('filled', sa.Integer(), nullable=False),
    sa.Column('healed', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('comment_outreach', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_table('prayer_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('prayer_group', sa.String(length=255), nullable=False),
    sa.Column('prayer_chain', sa.String(), nullable=True),
    sa.Column('retreat', sa.String(), nullable=True),
    sa.Column('vigil', sa.String(), nullable=True),
    sa.Column('comment_prayer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_table('study_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('study_group', sa.String(length=255), nullable=False),
    sa.Column('messages_listened', sa.String(length=255), nullable=True),
    sa.Column('book_read', sa.String(), nullable=True),
    sa.Column('comment_study', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_info')
    op.drop_table('prayer_info')
    op.drop_table('outreach_info')
    op.drop_table('followup_info')
    op.drop_table('worker')
    # ### end Alembic commands ###
