"""empty message

Revision ID: 5e9c05c64c7f
Revises: 6b5d1a237cdf
Create Date: 2023-06-15 03:33:10.276266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9c05c64c7f'
down_revision = '6b5d1a237cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_info', schema=None) as batch_op:
        batch_op.alter_column('study_group',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('messages_listened',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['worker_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('study_info', schema=None) as batch_op:
        batch_op.alter_column('messages_listened',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('study_group',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
